import type { Metadata } from "next";
import "../styles/globals.css";
import { roboto } from "@/app/fonts/fonts";
import Navigation from "@/components/layout/Navigation";
import Breadcrumb from "@/components/layout/Breadcrumb";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

export const metadata: Metadata = {
  title: "B Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        <Header />
        <Navigation />
        <Breadcrumb />
        {children}
        <Footer />
      </body>
    </html>
  );
}
